apiVersion: apps/v1
kind: Deployment

metadata:
  name: grayscale-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: grayscale

  template:
    metadata:
      labels:
        app: grayscale

    spec:
      containers:
        - name: grayscale-container
          image: europe-west2-docker.pkg.dev/fresh-airfoil-504422-p7/grayscale-repo/grayscale-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80